- menu_name: "Quick Links"

- name: "About"
  url: "/info/"
  title: "About Me"

- name: "Projects"
  url: "/projects/"
  title: "ML Projects"

- name: "Blog"
  url: "/blog/"
  title: "Blog"

- name: "Contact"
  url: "/contact/"
  title: "Contact"
